# Generated by Django 4.1.2 on 2022-11-09 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Carrera',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_carrera', models.IntegerField()),
                ('nombre', models.IntegerField()),
            ],
        ),
    ]
