# Generated by Django 4.1.2 on 2022-11-12 01:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Modulo', '0009_carrera2_alumno2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alumno2',
            name='id_carrera',
        ),
        migrations.DeleteModel(
            name='Carrera2',
        ),
        migrations.DeleteModel(
            name='Alumno2',
        ),
    ]
