# Generated by Django 4.1.2 on 2022-11-14 22:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Modulo', '0011_remove_administrador_id_cargo_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Administrador',
            fields=[
                ('id_admin', models.IntegerField(primary_key=True, serialize=False)),
                ('turno', models.CharField(max_length=50)),
                ('nombre', models.CharField(max_length=50)),
                ('apellidos', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Alumno',
            fields=[
                ('matricula', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('apellidos', models.CharField(max_length=50)),
                ('turno', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=50)),
                ('contraseña', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Cargo',
            fields=[
                ('id_cargo', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Carrera',
            fields=[
                ('id_carrera', models.IntegerField(primary_key=True, serialize=False)),
                ('nom_carrera', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Cuatrimestre',
            fields=[
                ('id_cuatrimestre', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre_cuatrimestre', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Docente_administrativo',
            fields=[
                ('id_doc_ad', models.IntegerField(primary_key=True, serialize=False)),
                ('turno', models.CharField(max_length=50)),
                ('nombre', models.CharField(max_length=50)),
                ('apellidos', models.CharField(max_length=50)),
                ('id_cargo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Modulo.cargo')),
                ('id_cuatrimestre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Modulo.cuatrimestre')),
            ],
        ),
        migrations.CreateModel(
            name='Libro',
            fields=[
                ('codigo_interno', models.IntegerField(primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=50)),
                ('autor', models.CharField(max_length=50)),
                ('existencia', models.IntegerField()),
                ('fecha_publicacion', models.DateField()),
                ('estado_libro', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id_usuario', models.IntegerField(primary_key=True, serialize=False)),
                ('id_admin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Modulo.administrador')),
                ('id_doc_ad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Modulo.docente_administrativo')),
                ('matricula', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Modulo.alumno')),
            ],
        ),
        migrations.AddField(
            model_name='alumno',
            name='id_carrera',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Modulo.carrera'),
        ),
        migrations.AddField(
            model_name='alumno',
            name='id_cuatrimestre',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Modulo.cuatrimestre'),
        ),
        migrations.AddField(
            model_name='administrador',
            name='id_cargo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Modulo.cargo'),
        ),
    ]
