# Generated by Django 4.1.2 on 2023-02-05 22:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Modulo', '0013_remove_administrador_id_cargo_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alumno',
            fields=[
                ('matricula', models.IntegerField(primary_key=True, serialize=False)),
                ('turno', models.CharField(max_length=50)),
                ('nombre_completo', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=50)),
                ('contraseña', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Carrera',
            fields=[
                ('id_carrera', models.IntegerField(primary_key=True, serialize=False)),
                ('nom_carrera', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Cuatrimestre',
            fields=[
                ('id_cuatrimestre', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre_cuatrimestre', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Det_Prestamo',
            fields=[
                ('cns', models.IntegerField(primary_key=True, serialize=False)),
                ('cant_libros', models.IntegerField()),
                ('estatus', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Prestamo',
            fields=[
                ('id_prestamo', models.IntegerField(primary_key=True, serialize=False)),
                ('fecha_prestamo', models.DateField()),
                ('fecha_devolucion', models.DateField()),
                ('matricula', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Modulo.alumno')),
            ],
        ),
        migrations.CreateModel(
            name='Libro',
            fields=[
                ('codigo_interno', models.IntegerField(primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=50)),
                ('autor', models.CharField(max_length=50)),
                ('disponibles', models.IntegerField()),
                ('estado_libro', models.CharField(max_length=50)),
                ('idioma', models.CharField(max_length=30)),
                ('editorial', models.CharField(max_length=50)),
                ('paginas', models.IntegerField()),
                ('imagen', models.ImageField(upload_to='')),
                ('carrera', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Modulo.carrera')),
            ],
        ),
        migrations.CreateModel(
            name='Historial_Sancions',
            fields=[
                ('const', models.IntegerField(primary_key=True, serialize=False)),
                ('sancion', models.CharField(max_length=100)),
                ('fecha_sancion', models.DateField()),
                ('fecha_vencimiento_sancion', models.DateField()),
                ('cns', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Modulo.det_prestamo')),
            ],
        ),
        migrations.AddField(
            model_name='det_prestamo',
            name='id_prestamo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Modulo.prestamo'),
        ),
        migrations.AddField(
            model_name='alumno',
            name='id_carrera',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Modulo.carrera'),
        ),
        migrations.AddField(
            model_name='alumno',
            name='id_cuatrimestre',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Modulo.cuatrimestre'),
        ),
    ]
